package:
  name: topomt
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - pip
  - setuptools >=61.0
  - versioningit ~=2.0
  run:
  - python
  - pip
  - setuptools >=61.0
  - versioningit ~=2.0
  - molsysmt
  - pyunitwizard
  - scipy
  - nglview
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library...

    '
  dev_url: https://github.com/uibcdf/topomt
  doc_url: https://uibcdf.org/topomt
