package:
  name: topomt
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - setuptools
  - numpy
  run:
  - python
  - setuptools
  - numpy
  - pyunitwizard
  - scipy
  - nglview
  - molsysmt
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library...

    '
  dev_url: https://github.com/uibcdf/topomt
  doc_url: https://uibcdf.org/topomt
